const palavras = [
    "Agregar",
    "Alavancar",
    "Alinhar",
    "Avaliação",
    "Background",
    "Benchmarking",
    "Branding",
    "Brainstorming",
    "Briefing",
    "Budget",
    "Brilho no olho",
    "Business plan",
    "Business unit",
    "Capital intelectual",
    "Capacitação",
    "Case",
    "CEO",
    "Clima",
    "Coaching",
    "Cultura",
    "Colaborador",
    "Comoditização",
    "Competência(s)",
    "Deadline",
    "Disruptivo",
    "Downsizing",
    "Endereçar",
    "Endomarketing",
    "Empowerment",
    "Está no DNA",
    "Expertise",
    "Feedback",
    "Follow up",
    "Ganha-ganha",
    "Headhunter",
    "Insight",
    "Interface",
    "Job",
    "Job rotation",
    "Job description",
    "Know-how",
    "Layout",
    "Mentoring",
    "Meritocracia",
    "Networking",
    "Outplacement",
    "On-the-job",
    "Ombudsman",
    "Outsourcing",
    "Fora da caixa",
    "Performar",
    "Período sabático",
    "Proativo",
    "Paradigma",
    "Resiliência",
    "Sinergia",
    "Schedular",
    "Startar",
    "Supply chain",
    "Team building",
    "To do",
    "Tropicalizar",
    "Turnover",
    "Workaholic",
    "Presidente",
    "Diretoria",
    "Executivos",
    "Conselho",
    "Conselheiro(s)",
    "Cliente(s)",
    "Cooperado(s)",
    "Ponto de Atendimento",
    "UAD",
    "Sobras",
    "Juros",
    "Selic",
    "Economia",
    "Governo",
    "Orçamento",
    "Time",
    "Grito de guerra",
    "Timaço",
    "Comunidade",
    "Agência",
    "Central",
    "Brasília",
    "Inovar",
    "Ideia(s)",
    "Nosso negócio",
    "Instituto",
    "Relatório",
    "Apresentação",
    "Power Point",
    "Excel",
    "AGO",
    "Delegado(s)",
    "Bom dia",
    "Boa tarde",
    "Boa noite",
    "Colega(s)",
    "Gerente(s)",
    "Regional",
    "Mercado",
    "Regionais",
    "Capital",
    "Aplicação",
    "Seguro",
    "Produtos",
    "Serviços",
    "Inovação",
    "Revolução",
    "Revolucionar",
    "Negócios",
    "Colaborar",
    "Intensificar",
    "Intensidade",
    "Legal",
    "Ótimo",
    "Parabéns",
    "Meta(s)",
    "LinkedIn",
    "Currículo",
    "RH",
    "DHO",
    "Startup",
    "Estudo",
    "Marketing",
    "Propaganda",
    "Publicidade",
    "Link",
    "Penetração",
    "Marketshare",
    "Usuário(s)",
    "Chave",
    "Alma",
    "Entrega",
    "Prazo",
    "Inadmissível",
    "Foco",
    "Tempo",
    "Aumento",
    "Ajuste",
    "Rota",
    "Seminário",
    "Fórum",
    "Confraternização",
    "Aniversariante",
    "Mascote",
    "Agenda",
    "Controle",
    "Visita",
    "Semanal",
    "Diário",
    "Assertivo",
    "Resiliente",
    "Pra mim",
    "Sucesso",
    "Organizacional",
    "Mudança",
    "Mindset",
    "Plus a mais",
    "Start inicial",
    "Anexar junto",
    "e-mail",
    "Crescimento",
    "Guia",
    "MBA",
    "Treinamento",
    "Banco(s)",
    "Crescer",
    "Crescemos",
    "Carteira",
    "Diminuiu",
    "Retorno",
    "Rede",
    "Taxa",
    "Crédito",
    "Demitir",
    "Demissão",
    "Equipe",
    "Colaboração",
    "Pós-graduação",
    "Estagiário",
    "Jovem aprendiz",
    "Commodity",
    "Coach",
    "Core business",
    "Business",
    "Forecast",
    "KPI",
    "OKR",
    "Superar",
    "Campanha",
    "Vendas",
    "Acelerador",
    "Performance",
    "Delivery",
    "Almoço",
    "Reunião",
    "Meeting",
    "Call",
    "Teams",
    "Vídeo",
    "Aplicativo",
    "Computador",
    "Erro(s)",
    "Liderança(s)",
    "Estratégia(s)",
    "Estratégico(s)",
    "Inteligência",
    "Start",
    "Target",
    "Alinhamento",
    "Digital",
    "Atendimento",
    "Diferencial",
    "Engajar",
    "Engajado",
    "Engajamento",
    "Motivar",
    "Motivação",
    "Motivado",
    "Férias",
    "Semestre",
    "Resultado(s)",
    "Ruim",
    "Bom",
    "Regular",
    "Melhor",
    "Anual",
    "Comissão",
    "Política",
    "Comitê",
    "Ética",
    "Disciplina",
    "Disciplinar",
    "Multa",
    "Squad",
    "Despesa(s)",
    "Receita(s)",
    "Balanço",
    "Interno",
    "Ambiente",
    "Externo",
    "Absorver",
    "Transferência",
    "Futuro",
    "Passado",
    "Segmento(s)",
    "Empresa(s)",
    "Rural",
    "Varejo",
    "Financiamento(s)",
    "Saldo",
    "Organograma",
    "Funcionário(s)",
    "Brasil",
    "Mundo",
    "Local",
    "Rotatividade",
    "Desligamento(s)",
    "Sofisticado(s)",
    "Impulsionar",
    "Propósito",
    "Diretriz(es)",
    "Análise",
    "Pessoal",
    "Profissional",
    "Certificação",
    "Projeto",
    "ESG",
    "Atitude(s)",
    "Trabalho",
    "Tarefa(s)",
    "Dia a dia",
    "Home office",
    "Dados",
    "Big data",
    "Artificial",
    "Power BI",
    "Site",
    "Rede Social",
    "Terceirizar",
    "Terceirização",
    "Curso(s)",
    "Hierarquia",
    "Júnior",
    "Pleno",
    "Sênior",
    "Analista(s)",
    "Supervisor",
    "Supervisão",
    "Gerência",
    "Compliance",
    "Auditoria",
    "Resposta",
    "Líder",
    "Dossiê",
    "Assunto",
    "Encaminhar",
    "Falha",
    "Responsabilidade(s)",
    "Expansão",
    "Plano",
    "São Paulo",
    "Interior",
    "Região",
    "Captação",
    "Comportamento",
    "Manual",
    "Instrução",
    "Norma(s)",
    "Procuração",
    "Procurador",
    "Calendário",
    "Contábil",
    "Contabilizar",
    "Contabilização",
    "Conhecimento",
    "Habilidade(s)",
    "Processo(s)",
    "Mapear",
    "Mapeamento",
    "Levantamento",
    "Levantar",
    "Autonomia",
    "Informação",
    "Administração",
    "Decisão",
    "Empoderamento",
    "Empoderar",
    "Mulheres",
    "Homens",
    "Jovens",
    "Atuação",
    "Cooperativa",
    "Singular",
    "Organização",
    "Especialista(s)",
    "Ferramenta(s)",
    "Gestão",
    "Desempenho",
    "Acompanhamento",
    "Top-down",
    "Bottom-up",
    "Operacional",
    "Tático",
    "Solução",
    "Recursos Humanos",
    "Departamento(s)",
    "Função",
    "Cargo(s)",
    "Design",
    "Experiência(s)",
    "Carreira",
    "Multitarefa(s)",
    "Multidisciplinar(es)",
    "Promoção",
    "Conflito(s)",
    "Mão de obra",
    "Terceiro(s)",
    "Parceiro(s)",
    "Parceria(s)",
    "Padrão",
    "Superação",
    "Stakeholder(s)",
    "Soluções",
    "Inovador(a)",
    "Capacidade(s)",
    "Suprimento(s)",
    "Matriz",
    "Risco(s)",
    "Valor",
    "Valores",
    "Lista(s)",
    "Presidência",
    "Prospecção",
    "Felicidade",
    "Transparência",
    "Gratidão",
    "Governança",
    "Área(s)",
    "Encontro",
    "Fácil"
];

const cartela = [];
for(i=0; i<24; i++){
    cartela[i]=null;
}

cartela[0]=palavras[Math.floor(Math.random() * (palavras.length+1))];

for(i=1; i<24; i++){
    cartela[i]=palavras[Math.floor(Math.random() * (palavras.length+1))];
    for(j=0; j<i; j++){
        do{
            if(cartela[i].includes(cartela[j])){
                cartela[i]=palavras[Math.floor(Math.random() * (palavras.length+1))];
            }
        }while(cartela[i].includes(cartela[j]));
    }
}

cartela.sort();